#!/bin/bash

dereferenceSymlink() {
  local linkPath="$1";
  local realPath;
  while [ -L "$linkPath" ]; do
    realPath="$(readlink "${linkPath}")";
    if [ ${realPath:0:1} != '/' ]; then
      realPath="$(dirname "${linkPath}")/${realPath}";
    fi
    linkPath="${realPath}";
  done
  fullPath "${linkPath}";
}

for l in "$@"; do
	dereferenceSymlink "$l";
done

## NOTES:
# 2022-12-02 Preferring a Bash implementation for BSD compatibility.
# 2022-08-31 Could replace all 'canon' with 'readlink -f' (on GNU systems).
