#!/bin/bash

# --no-renames: does this cause larger diffs, because a rename is treated more like a mode change, not a code change?
diff_reference=$1
if [[ -z $diff_reference ]]; then
	remote=origin
	if [[ -z $(git remote | grep "\<$remote\>") ]]; then
		remote=$(git branch -vv | grep '^\*' | perl -pe 's;^.* \[([^/]+).*;\1;')
		if [[ $remote =~ ^\* ]]; then # no upstream branch found
			remote=""
		fi
	fi
	if [[ -n $remote ]]; then
		remote_head_branch=develop
		if [[ -z $(git branch | grep "\<$remote_head_branch\>") ]]; then
			remote_head_branch=$(git remote show $remote | grep 'HEAD branch' | perl -pe 's/^\s*HEAD branch:\s*//')
		fi
		if [[ -n $remote_head_branch ]]; then
			diff_reference=$remote/$remote_head_branch
		fi
	fi
fi

findTodos() {
  local rootGitDir="$(git rev-parse --show-cdup)"
  [[ -n $rootGitDir ]] && cd "$rootGitDir"
  if [[ -n $diff_reference ]]; then
    git diff -U0 $diff_reference | grep '^+++\|^+.*\(FIXME\|XXX\|TODO\)' | perl -pe 's/^\++( b\/)?//'| grep -B 1 --color=always 'FIXME\|XXX\|TODO'
  else
    git grep -n --color=always -n '\(FIXME\|XXX\|TODO\)'
  fi
}

if [[ -t 1 ]]; then
  # findTodos | less -RS
  findTodos | more
else
  findTodos
fi

# HISTORY
# v? 2024-12-26 Explicit git command for root dir.  b2sum=564fcd40&size=1042
