#!/bin/bash
SCRIPT_VERSION='0.6.1 2026-03-19'
SCRIPT_UUID='60dffac9-3444-41bb-bdf6-c9c63cdee89d'
#SYNC_CONF_FILENAME='.sync.conf'
SYNC_CONF_PATTERN='.sync*.conf'
SCRIPT_PATH="$0"
[[ -L "$SCRIPT_PATH" ]] && SCRIPT_PATH="$(readlink --canonicalize "$SCRIPT_PATH")" # Allow linking, but find original for dependencies and tasks. FIXME: Assuming GNU readlink.
SCRIPT_NAME="$(basename "$SCRIPT_PATH")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
PATH_READ_CONF_SOURCE="$SCRIPT_DIR/read-config.sh"
oIFS="$IFS"
shopt -s extglob
declare -A opt
opt[ASSUMEYES]=0
opt[BASE]="$PWD"
opt[DRYRUN]=FALSE
opt[SHOWHELP]=0
opt[VERBOSE]=0

isdry() { [[ ${opt[DRYRUN]} == TRUE ]]; }
loglevel() { [[ ${opt[VERBOSE]} -ge $1 ]]; }
feedback() { loglevel $1 || return; shift; >&2 echo "$@"; }
showHelp()
{
  echo "SYNOPSIS: Copies files from wherever a ${SYNC_CONF_PATTERN} file is found."
  echo
  echo "USAGE: sync [-h|--help] [-n|--dry-run] [-y|--no-prompt] [-v[v…]|--verbose|-q|--quiet] [PATH]"
  echo
  echo "CONFIG (see shell-utilities/read-config.sh):"
  echo "  destination=PATH"
  echo "  subdir=DATEFORMAT"
  echo "  exclude=PATTERN or ('PATTERN'…) # applies before include (*regardless of CONFIG line order)"
  echo "  include=PATTERN or ('PATTERN'…) # applies after exclude (^*)"
  echo "  keepcopy=true|false"
  echo "  postprocess=COMMAND # where \$1 is the destination (sub)directory. Runs after all sync operations."
  echo "  [HOSTNAME] # groups"
  echo
  echo "NOTE: Only one value is assigned per key in the CONFIG. Multiples overwrite earlier values."
  echo " Some keys (include, exclude) are evaluated to support arrays, like key=('a' 'b')."
  echo
  echo "OPTIONS:"
  echo "  PATH  Path to directory to search for ${SYNC_CONF_PATTERN} files. Defaults to \$PWD."
  echo "  -h,--help  Show this help."
  echo "  -n,--dry-run  Make no changes, move no files. Find ${SYNC_CONF_PATTERN} files, and print commands. Implies -y."
  echo "  -y,--no-prompt  Begin syncing without prompting the user first."
  echo "  -v,--verbose  Show more info. Can be used multiple times."
  echo "  -q,--quiet  Suppress most output."

  local todoPath="${SCRIPT_DIR}/todo.${SCRIPT_NAME}.txt"
  if loglevel 1 && [[ -s "$todoPath" ]]
  then
    echo
    echo "TODO (${todoPath}):"
    cat "$todoPath" \
      | sed 's/^/  /'
  fi

  echo
  echo "VERSION: ${SCRIPT_VERSION}"
}

while [[ $# -gt 0 ]]
do
  case $1 in
    -h|--help)
      opt[SHOWHELP]=TRUE
      ;;
    -n|--dry-run)
      opt[DRYRUN]=TRUE
      opt[ASSUMEYES]=1
      ;;
    -+(v))
      let "opt[VERBOSE] += ${#1} - 1"
      ;;
    --verbose)
      let opt[VERBOSE]++
      ;;
    -y|--no-prompt)
      opt[ASSUMEYES]=1
      ;;
    -q|--quiet)
      opt[VERBOSE]=-1
      ;;
    -d) # sunset 2026-03-13/2026-06
      opt[BASE]="$2"
      shift
      ;;
    *)
      opt[BASE]="$1"
      ;;
  esac
  shift
done

feedback 1 "# [${SCRIPT_NAME}] Log level: ${opt[VERBOSE]}"

if [[ ${opt[SHOWHELP]} == TRUE ]]
then
  showHelp
  exit
else
  feedback 1 "# [${SCRIPT_NAME}] version: ${SCRIPT_VERSION}"
fi

if isdry
then
  feedback 0 "# [${SCRIPT_NAME}] DRY RUN: no changes to files; find only"
fi

baseFindArgs=()
baseFindArgs+=("${opt[BASE]}" -name "$SYNC_CONF_PATTERN")
feedback 0 "Finding sync config files:"
feedback 2 "# [${SCRIPT_NAME}] $ find ${baseFindArgs[*]} -print0"
configPaths=()
while IFS= read -r -d $'\0' path <&3
do
  configPaths+=("$path")
  feedback 0 "  $path"
  if loglevel 1
  then
    cat "$path" | sed 's/^/  │  /' # U=2502 Box Drawings Light Vertical
    feedback 1
  fi
done 3< <(find "${baseFindArgs[@]}" -print0)
baseFindStatus=$?
IFS="$oIFS"
if [[ $baseFindStatus -ne 0 || ${#configPaths[@]} -eq 0 ]]
then
  feedback 0 "Failed to find any sync config files (status ${baseFindStatus}). Aborting."
  exit
fi

# TODO Parse config before prompting, not only ^ displaying config text.  todo.sync.txt#8b304e92

if [[ ${opt[ASSUMEYES]} -le 0 ]]
then
  read -p "Proceed to sync these directories? (Y/n): " \
    && [[ -z $REPLY || $REPLY =~ ^[Yy] ]] \
    || exit
fi

feedback 0 -E "# [${SCRIPT_NAME}] BEGIN $(date --iso-8601=seconds)"

export SCRIPT_NAME
export PATH_READ_CONF_SOURCE

syncCommand=''
#syncCommand+="SCRIPT_NAME=\"${SCRIPT_NAME}\"; "
loglevel 2 && syncCommand+='declare -p PWD; '
syncCommand+=". \"\$PATH_READ_CONF_SOURCE\" || exit; "
syncCommand+='read-config '
  loglevel 2 && syncCommand+='-v '
  syncCommand+='-u -c "$HOSTNAME" -f {}; '
syncCommand+='destination="${config[destination]}/$(date "+${config[subdir]}")"; '
syncCommand+='destination="${destination%%/}"; '
syncCommand+='if [[ -z $destination ]]; then >&2 echo "Empty destination. Skipping file transfer."; exit; fi; '
! isdry && syncCommand+='mkdir -p "$destination"; '
syncCommand+='rsyncArgs=(); '
isdry && syncCommand+='rsyncArgs+=(--dry-run); '
loglevel 1 && syncCommand+='rsyncArgs+=(-v); '
loglevel 2 && syncCommand+='rsyncArgs+=(--debug=FILTER); '
#loglevel 0 && syncCommand+='rsyncArgs+=(--info=progress2); '
syncCommand+='rsyncArgs+=(-r); '
syncCommand+="rsyncArgs+=(--exclude=\"${SYNC_CONF_PATTERN}\"); "
syncCommand+='if [[ -n ${config[include]} ]]; then '
  syncCommand+='includePatterns=(); '
  syncCommand+="if [[ \${config[include]} =~ [\\\"\\'()] ]]; "
  syncCommand+='then '
    syncCommand+='eval "includePatterns+=${config[include]}"; '
  syncCommand+='else '
    syncCommand+='includePatterns+=("${config[include]}"); '
  syncCommand+='fi; '
  loglevel 2 && syncCommand+='>&2 echo "# [${SCRIPT_NAME}] includePatterns(${#includePatterns[@]}): ${includePatterns[*]}"; '
  syncCommand+='for pattern in "${includePatterns[@]}"; '
  syncCommand+='do '
    syncCommand+='rsyncArgs+=(--include="${pattern}"); '
  syncCommand+='done; '
  #syncCommand+='if [[ ${#includePatterns[@]} -gt 0 ]]; then '
  #  syncCommand+='rsyncArgs+=(--exclude="*"); '
  #syncCommand+='fi '
syncCommand+='fi; '
syncCommand+='if [[ -n ${config[exclude]} ]]; then '
  syncCommand+='excludePatterns=(); '
  syncCommand+="if [[ \${config[exclude]} =~ [\\\"\\'()] ]]; "
  syncCommand+='then '
    syncCommand+='eval "excludePatterns+=${config[exclude]}"; '
  syncCommand+='else '
    syncCommand+='excludePatterns+=("${config[exclude]}"); '
  syncCommand+='fi; '
  loglevel 2 && syncCommand+='>&2 echo "# [${SCRIPT_NAME}] excludePatterns(${#excludePatterns[@]}): ${excludePatterns[*]}"; '
  syncCommand+='for pattern in "${excludePatterns[@]}"; '
  syncCommand+='do '
    syncCommand+='rsyncArgs+=(--exclude="${pattern}"); '
  syncCommand+='done; '
syncCommand+='fi; '
syncCommand+='[[ ${config[keepcopy]} != true ]] && rsyncArgs+=(--remove-source-files); '
syncCommand+='rsyncArgs+=("$PWD/" "$destination/"); '
loglevel 1 && syncCommand+='>&2 echo "# [${SCRIPT_NAME}] \$ rsync ${rsyncArgs[*]}"; '; 
syncCommand+='rsync "${rsyncArgs[@]}"; '

feedback 0
feedback 0 "# [${SCRIPT_NAME}] PHASE: sync"
# Higher loglevel because syncCommand prints rsync command if loglevel 1.
feedback 2 -E "# [${SCRIPT_NAME}] syncCommand: ${syncCommand}"
feedback 2 # newline for legibility
syncFindArgs=()
syncFindArgs+=("${baseFindArgs[@]}")
loglevel 0 && syncFindArgs+=(-print)
syncFindArgs+=(-execdir bash -c "$syncCommand" \;) # NOTE sync will be no-op if isdry
find "${syncFindArgs[@]}"


#postprocessCommand+="SCRIPT_NAME=\"${SCRIPT_NAME}\"; "
loglevel 2 && postprocessCommand+='declare -p PWD; '
postprocessCommand+=". \"\$PATH_READ_CONF_SOURCE\" || exit; "
postprocessCommand+='read-config '
  loglevel 2 && postprocessCommand+='-v '
  postprocessCommand+='-u -c "$HOSTNAME" -f {}; '
postprocessCommand+='destination="${config[destination]}/$(date "+${config[subdir]}")"; '
postprocessCommand+='destination="${destination%%/}"; '
postprocessCommand+='if [[ -z $destination ]]; then >&2 echo "Empty destination. Assuming PWD \"$PWD\"."; destination="$PWD"; fi; '
postprocessCommand+='[[ -n ${config[postprocess]} ]] && { '
  postprocessCommand+='eval "postprocess() { ${config[postprocess]}'$'\n''}" && type postprocess '
    ! loglevel 1 && postprocessCommand+='&>/dev/null '
  if isdry
  then
    postprocessCommand+='; '
  else
    postprocessCommand+='&& '
    postprocessCommand+='if [[ ${config[background]} == true ]]; then '
      postprocessCommand+='postprocess "$destination" & '
    postprocessCommand+='else '
      postprocessCommand+='postprocess "$destination"; '
    postprocessCommand+='fi; '
  fi
postprocessCommand+='}'

feedback 0
feedback 0 "# [${SCRIPT_NAME}] PHASE: post process"
feedback 2 -E "# [${SCRIPT_NAME}] postprocessCommand: ${postprocessCommand}"
feedback 2 # newline for legibility
postProcessFindArgs=()
postProcessFindArgs+=("${baseFindArgs[@]}")
postProcessFindArgs+=(-exec grep -q '^\s*postprocess=' {} \;)
postProcessFindArgs+=(-execdir bash -c "$postprocessCommand" \;) # NOTE postprocess will be no-op if isdry
loglevel 0 && postProcessFindArgs+=(-print)
find "${postProcessFindArgs[@]}"

feedback 0
feedback 0 -E "# [${SCRIPT_NAME}] END $(date --iso-8601=seconds)"

